#!/usr/bin/env bash
#
# Regenerates the tray icons. NOT part of `compile` — only re-run when the
# brand mark changes, and it wants tools (python3 + fontTools, rsvg-convert)
# that a plain build should not require.
#
#   ./scripts/make-tray-icons.sh
#
# Produces TWO tray rasters per resolution (18×18 + 36×36):
#
#   assets/trayTemplate.png / @2x.png   MONOCHROME (single-colour path) for
#                                       macOS, marked template with
#                                       setTemplateImage(true) so the system
#                                       can tint it for light/dark menu bars.
#   assets/trayColor.png / @2x.png      FULL-COLOUR raster (the brand gradient
#                                       tile) for Windows and Linux, where the
#                                       tray cannot be tinted and the
#                                       monochrome version would render as a
#                                       black square.
#
# `tray.ts` picks the right one per platform at runtime.
#
# The macOS template raster is generated from `icon-mono-path.svg`, the bare
# path of the brand mark — the same source the extension's codicon font
# builder uses. The source declares viewBox="0 0 32 32" but the path actually
# spans ~35.77 x 36.25, so rendering verbatim CLIPS the bottom-right. We
# fit the real bbox (fontTools BoundsPen), the same trick the font builder
# uses — that's the whole reason this script exists rather than just calling
# rsvg-convert on the source SVG.
set -euo pipefail

cd "$(dirname "$0")/.."
SRC_MONO="../copilot/media/icon-mono-path.svg"
SRC_COLOR="../copilot/icon.svg"

for tool in python3 rsvg-convert; do
  command -v "$tool" >/dev/null || { echo "missing: $tool" >&2; exit 1; }
done

python3 - "$SRC_MONO" <<'PY'
# Render the bare path into a 32×32 viewBox SVG that doesn't clip it.
# `path` is black so the macOS template tint can recolour it.
import re, sys
from fontTools.svgLib.path import parse_path
from fontTools.pens.boundsPen import BoundsPen

src = sys.argv[1]
d = max(re.findall(r'<path\s+d="([^"]+)"', open(src).read()), key=len)
pen = BoundsPen(None)
parse_path(d, pen)
x0, y0, x1, y1 = pen.bounds
w, h = x1 - x0, y1 - y0
# ~5% breathing room so the badge does not touch the menu-bar edges.
side = max(w, h) * 1.05
left = x0 + w / 2 - side / 2
top = y0 + h / 2 - side / 2

open("assets/icon-mono.svg", "w").write(f'''<!--
  Generated by scripts/make-tray-icons.sh from {src} — do not edit by hand.

  That source declares viewBox="0 0 32 32" but the path actually spans
  x[{x0:.2f},{x1:.2f}] y[{y0:.2f},{y1:.2f}], so rendering it as-is CLIPS the mark.
  The extension's font builder fits the path's real bbox the same way, which is
  why this exists: the macOS template tray icon has to match the status-bar
  glyph.
-->
<svg xmlns="http://www.w3.org/2000/svg" width="{side:.2f}" height="{side:.2f}"
     viewBox="{left:.2f} {top:.2f} {side:.2f} {side:.2f}" fill="none">
  <path d="{d}" fill="#000000" fill-rule="evenodd"/>
</svg>
''')
print(f"assets/icon-mono.svg  viewBox={left:.2f} {top:.2f} {side:.2f} {side:.2f}")
PY

# macOS template (monochrome): the bare path, single colour, marked template
# at runtime by tray.ts. 18pt is the macOS menu bar height; @2x is retina.
rsvg-convert -w 18 -h 18 assets/icon-mono.svg -o assets/trayTemplate.png
rsvg-convert -w 36 -h 36 assets/icon-mono.svg -o assets/trayTemplate@2x.png

# Windows / Linux: the FULL brand mark (gradient tile + path), shown as-is.
rsvg-convert -w 18 -h 18 "$SRC_COLOR" -o assets/trayColor.png
rsvg-convert -w 36 -h 36 "$SRC_COLOR" -o assets/trayColor@2x.png

echo "wrote assets/trayTemplate.png (@2x) — macOS template"
echo "wrote assets/trayColor.png (@2x)    — Windows / Linux"
