#!/usr/bin/env bash
#
# Regenerates the macOS template tray icon. NOT part of `compile` — only
# re-run when the BARE MARK path changes (the same source the VS Code
# extension's codicon font builder uses), and it wants tools
# (python3 + fontTools, rsvg-convert) that a plain build should not require.
#
#   ./scripts/make-tray-icons.sh
#
# Produces the macOS template raster only:
#
#   assets/trayTemplate.png / @2x.png   MONOCHROME (single-colour path).
#                                       macOS, marked template at runtime by
#                                       tray.ts so the system tints it to
#                                       match light/dark menu bars.
#
# Out of scope (separate scripts with separate sources):
#   - assets/icon.png / .icns / .ico     `make-app-icon.sh`
#   - assets/trayColor.png / @2x.png    `make-app-icon.sh`
#   - VS Code status-bar glyph font     `build-codicon-font.py` in
#                                       packages/copilot/scripts
#
# Why split this from the colored assets: the colored tray + app icons are
# tied to the FULL brand tile (gradient + glow + cat) and change every
# time the background is recolored. The macOS template only depends on
# the bare mark path — when the user tweaks the gradient the template
# must not be touched (rsvg-convert on the same source is deterministic,
# but a touch is still churn that shows up in git, and there is no reason
# to rewrite a file whose input has not changed).
#
# The source declares viewBox="0 0 32 32" but the path actually spans
# ~35.77 x 36.25, so rendering it verbatim CLIPS the bottom-right. We
# fit the real bbox (fontTools BoundsPen), the same trick the font
# builder uses.
set -euo pipefail

cd "$(dirname "$0")/.."
SRC_MONO="../copilot/media/icon-mono-path.svg"

for tool in python3 rsvg-convert; do
  command -v "$tool" >/dev/null || { echo "missing: $tool" >&2; exit 1; }
done

python3 - "$SRC_MONO" <<'PY'
# Render the bare path into a 32×32 viewBox SVG that doesn't clip it.
# `path` is black so the macOS template tint can recolour it.
import re, sys
from fontTools.svgLib.path import parse_path
from fontTools.pens.boundsPen import BoundsPen

src = sys.argv[1]
d = max(re.findall(r'<path\s+d="([^"]+)"', open(src).read()), key=len)
pen = BoundsPen(None)
parse_path(d, pen)
x0, y0, x1, y1 = pen.bounds
w, h = x1 - x0, y1 - y0
# ~5% breathing room so the badge does not touch the menu-bar edges.
side = max(w, h) * 1.05
left = x0 + w / 2 - side / 2
top = y0 + h / 2 - side / 2

open("assets/icon-mono.svg", "w").write(f'''<!--
  Generated by scripts/make-tray-icons.sh from {src} — do not edit by hand.

  That source declares viewBox="0 0 32 32" but the path actually spans
  x[{x0:.2f},{x1:.2f}] y[{y0:.2f},{y1:.2f}], so rendering it as-is CLIPS the mark.
  The extension's font builder fits the path's real bbox the same way, which is
  why this exists: the macOS template tray icon has to match the status-bar
  glyph.
-->
<svg xmlns="http://www.w3.org/2000/svg" width="{side:.2f}" height="{side:.2f}"
     viewBox="{left:.2f} {top:.2f} {side:.2f} {side:.2f}" fill="none">
  <path d="{d}" fill="#000000" fill-rule="evenodd"/>
</svg>
''')
print(f"assets/icon-mono.svg  viewBox={left:.2f} {top:.2f} {side:.2f} {side:.2f}")
PY

# macOS template (monochrome): the bare path, single colour, marked template
# at runtime by tray.ts. 18pt is the macOS menu bar height; @2x is retina.
rsvg-convert -w 18 -h 18 assets/icon-mono.svg -o assets/trayTemplate.png
rsvg-convert -w 36 -h 36 assets/icon-mono.svg -o assets/trayTemplate@2x.png

echo "wrote assets/trayTemplate.png + trayTemplate@2x.png — macOS template"
echo "(the colored tray + app icon are NOT touched by this script; run"
echo " make-app-icon.sh for those when the brand tile changes)"
